# Generated by Django 6.0.3 on 2026-04-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medicalrecord_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(blank=True, choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('general', 'General Practitioner')], max_length=50, null=True),
        ),
    ]
